chirper/config/routes.rb
Rails.application.routes.draw do
  resources :chirps

end

chirper/app/models/chirp.rb
class Chirp < ActiveRecord::Base
end

chirper/app/controllers/chirps_controller.rb
class ChirpsController < ApplicationController
  before_action :set_chirp, only: [:show, :edit, :update, :destroy]

  # GET /chirps
  # GET /chirps.json
  def index
    @chirps = Chirp.all
  end

  # GET /chirps/1
  # GET /chirps/1.json
  def show
  end

  # GET /chirps/new
  def new
    @chirp = Chirp.new
  end

  # GET /chirps/1/edit
  def edit
  end

  # POST /chirps
  # POST /chirps.json
  def create
    @chirp = Chirp.new(chirp_params)

    respond_to do |format|
      if @chirp.save
        format.html { redirect_to @chirp, notice: 'Chirp was successfully created.' }
        format.json { render :show, status: :created, location: @chirp }
      else
        format.html { render :new }
        format.json { render json: @chirp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chirps/1
  # PATCH/PUT /chirps/1.json
  def update
    respond_to do |format|
      if @chirp.update(chirp_params)
        format.html { redirect_to @chirp, notice: 'Chirp was successfully updated.' }
        format.json { render :show, status: :ok, location: @chirp }
      else
        format.html { render :edit }
        format.json { render json: @chirp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chirps/1
  # DELETE /chirps/1.json
  def destroy
    @chirp.destroy
    respond_to do |format|
      format.html { redirect_to chirps_url, notice: 'Chirp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chirp
      @chirp = Chirp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chirp_params
      params.require(:chirp).permit(:author, :message)
    end
end

chirper/app/helpers/chirps_helper.rb
module ChirpsHelper
end

chirper/app/views/chirps/_form.html.erb
<%= form_for(@chirp) do |f| %>
  <% if @chirp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chirp.errors.count, "error") %> prohibited this chirp from being saved:</h2>

      <ul>
      <% @chirp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

chirper/app/views/chirps/edit.html.erb
<h1>Editing Chirp</h1>

<%= render 'form' %>

<%= link_to 'Show', @chirp %> |
<%= link_to 'Back', chirps_path %>

chirper/app/views/chirps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chirps</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chirps.each do |chirp| %>
      <tr>
        <td><%= chirp.author %></td>
        <td><%= chirp.message %></td>
        <td><%= link_to 'Show', chirp %></td>
        <td><%= link_to 'Edit', edit_chirp_path(chirp) %></td>
        <td><%= link_to 'Destroy', chirp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chirp', new_chirp_path %>

chirper/app/views/chirps/new.html.erb
<h1>New Chirp</h1>

<%= render 'form' %>

<%= link_to 'Back', chirps_path %>

chirper/app/views/chirps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @chirp.author %>
</p>

<p>
  <strong>Message:</strong>
  <%= @chirp.message %>
</p>

<%= link_to 'Edit', edit_chirp_path(@chirp) %> |
<%= link_to 'Back', chirps_path %>

chirper/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chirper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>